### ISSUE TITLE
Multi-stage builds: COPY cannot directly reference external images

### ISSUE THREAD

**Issue by sirlatrom** [jessfraz/img#17]
With `docker image build`, it is possible (yet undocumented, I think?) to specify e.g.
```Dockerfile
FROM scratch
COPY --from=consul:1.0.6 /bin/consul /bin/consul
```

With `img`, the build fails with
```
solving failed: stage consul:1.0.6 not found
```

To get the same functionality with `img`, I have to add a separate `FROM` line for it to work, like so:
```Dockerfile
FROM consul:1.0.6 AS consul
FROM scratch
COPY --from=consul /bin/consul /bin/consul
```

**Comment by sirlatrom** [comment]
PS: I'm suddenly aware this is possibly an upstream thing, perhaps in buildkit.

**Comment by AkihiroSuda** [comment]
Yes, this is a buildkit issue.
cc @tonistiigi @vdemeester

**Comment by sirlatrom** [comment]
Thanks, I've opened https://github.com/moby/buildkit/issues/287. Close this issue or leave it to track progress in buildkit as appropriate.

**Comment by AkihiroSuda** [comment]
will be fixed after vendoring the latest buildkit 
https://github.com/moby/buildkit/pull/288
