### ISSUE TITLE
img pull does not use default docker registry

### ISSUE THREAD

**Issue by stapelberg** [jessfraz/img#26]
The README states that `img` is a drop-in replacement for `docker` (at least for the mentioned subcommands), but the following doesn’t work (whereas the docker variant does):

```
% img pull stapelberg/ci2
Pulling stapelberg/ci2:latest...
INFO[0000] resolving stapelberg/ci2:latest              
failed to do request: Head https://stapelberg/v2/ci2/manifests/latest: dial tcp: lookup stapelberg on 10.0.0.1:53: no such host
```

**Comment by jessfraz** [comment]
thanks I pushed a fix :)

keep finding issues :)
