### ISSUE TITLE
Publish to Docker Hub?

### ISSUE THREAD

**Issue by sparty02** [jessfraz/img#33]
Would you be willing to add the img image to your jessfraz space in Docker Hub?

**Comment by jessfraz** [comment]
It should be there :) https://hub.docker.com/r/jess/img/

**Comment by sparty02** [comment]
Ah!  Sorry, the jess vs jessfraz thing threw me  :)

**Comment by jessfraz** [comment]
ah damn I have been meaning to mirror them all hahaha
