### ISSUE TITLE
solving failed: invalid filename when using path to dockerfile

### ISSUE THREAD

**Issue by ey-** [jessfraz/img#50]
I am used to build an image which Dockerfile is in a subfolder like images/bla/Dockerfile.
This is possible with docker by:

`docker build -f images/bla/Dockerfile .`

which makes the whole project available as context but still keeps the root directory save.

Doing the same with img results into:
`img build -f images/bla/Dockerfile .`
`solving failed: invalid filename: images/bla/Dockerfile`

**Comment by jessfraz** [comment]
working on this, thanks :)
